.SUFFIXES:
.SUFFIXES: .c .cpp .o

# Macro Definition
DEBUG    = -g -pg
OPT      = -O2
CC       = gcc
CFLAGS   = $(OPT) -Wall -std=gnu99 `sdl-config --cflags` $(DEBUG)
CXX      = g++
CXXFLAGS = -O2 -Wall `sdl-config --cflags` $(DEBUG)
LD       = gcc
LDFLAGS  = $(DEBUG)
INCLUDES = -I.
LIBS     = `sdl-config --libs` -lSDL_gfx -lGL -lGLU
RM       = rm -f
PROF     = gprof
TARGET   = water3d
OBJS     = main.o imgscale.o

# Rules
all: Makefile $(TARGET)
run: $(TARGET)
	./$(TARGET)
profile:
	$(PROF) $(TARGET) gmon.out | less
$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
clean:
	$(RM) $(TARGET) $(OBJS) gmon.out tags *~
.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $<
.cpp.o:
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $<

# Dependency(Generated by 'gcc -MM *.c')
imgscale.o: imgscale.c imgscale.h
main.o: main.c imgscale.h cpuidutil.h


